/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityEntryEditor: typeof import('./src/components/ActivityEntryEditor.vue')['default']
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BAvatar: typeof import('bootstrap-vue-next')['BAvatar']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next')['BCardFooter']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next')['BDropdownForm']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropdownItemButton: typeof import('bootstrap-vue-next')['BDropdownItemButton']
    BDropdownText: typeof import('bootstrap-vue-next')['BDropdownText']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTag: typeof import('bootstrap-vue-next')['BFormTag']
    BFormTags: typeof import('bootstrap-vue-next')['BFormTags']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BFormValidFeedback: typeof import('bootstrap-vue-next')['BFormValidFeedback']
    BInput: typeof import('bootstrap-vue-next')['BInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    ClockSolid: typeof import('./src/components/icons/clock-solid.vue')['default']
    CustomSpinner: typeof import('./src/components/CustomSpinner.vue')['default']
    EntryEditor: typeof import('./src/components/EntryEditor.vue')['default']
    HoursEntryModal: typeof import('./src/components/HoursEntryModal.vue')['default']
    IBiFill: typeof import('~icons/bi/fill')['default']
    IBiTagFill: typeof import('~icons/bi/tag-fill')['default']
    IBiX: typeof import('~icons/bi/x')['default']
    NavTopBar: typeof import('./src/components/NavTopBar.vue')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagDropdown: typeof import('./src/components/tagDropdown.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBModal: typeof import('bootstrap-vue-next')['vBModal']
  }
}
