version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - server/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  server:
    image: ghcr.io/educorvi/timeclicker:1-latest
    restart: always
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    container_name: timeclicker-server
    environment:
      DB_HOST: db
      DB_PORT: 5432
    env_file:
      - server/.env
    ports:
      - "3000:3000"
